#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove config and logs on purge (not on plain remove)
        rm -rf /etc/dpm
        rm -rf /var/log/dpm
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        ;;

    remove)
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dpm-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
