#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop dpm-agent.service || true
            systemctl disable dpm-agent.service || true
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dpm-agent.service' >/dev/null || true
fi
# End automatically added section


exit 0
