"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class log_chunk_t(object):
    __slots__ = ["protocol_version", "request_seq", "timestamp", "hostname", "name", "chunk_index", "last", "content"]

    __typenames__ = ["int32_t", "int64_t", "int64_t", "string", "string", "int32_t", "boolean", "string"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.protocol_version = 0
        self.request_seq = 0
        self.timestamp = 0
        self.hostname = ""
        self.name = ""
        self.chunk_index = 0
        self.last = False
        self.content = ""

    def encode(self):
        buf = BytesIO()
        buf.write(log_chunk_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iqq", self.protocol_version, self.request_seq, self.timestamp))
        __hostname_encoded = self.hostname.encode('utf-8')
        buf.write(struct.pack('>I', len(__hostname_encoded)+1))
        buf.write(__hostname_encoded)
        buf.write(b"\0")
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ib", self.chunk_index, self.last))
        __content_encoded = self.content.encode('utf-8')
        buf.write(struct.pack('>I', len(__content_encoded)+1))
        buf.write(__content_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != log_chunk_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return log_chunk_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = log_chunk_t()
        self.protocol_version, self.request_seq, self.timestamp = struct.unpack(">iqq", buf.read(20))
        __hostname_len = struct.unpack('>I', buf.read(4))[0]
        self.hostname = buf.read(__hostname_len)[:-1].decode('utf-8', 'replace')
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.chunk_index = struct.unpack(">i", buf.read(4))[0]
        self.last = bool(struct.unpack('b', buf.read(1))[0])
        __content_len = struct.unpack('>I', buf.read(4))[0]
        self.content = buf.read(__content_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if log_chunk_t in parents: return 0
        tmphash = (0x9ecc68897ebe8d1e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if log_chunk_t._packed_fingerprint is None:
            log_chunk_t._packed_fingerprint = struct.pack(">Q", log_chunk_t._get_hash_recursive([]))
        return log_chunk_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", log_chunk_t._get_packed_fingerprint())[0]

